# Generated by Django 3.1.3 on 2020-12-08 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0011_likecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes_com',
            field=models.ManyToManyField(related_name='liked_comments', through='manager.LikeComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
