# Generated by Django 3.1.3 on 2020-12-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_auto_20201210_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratebookuser',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
