# Generated by Django 3.1.3 on 2020-12-10 18:27

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('manager', '0018_auto_20201210_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
