# Generated by Django 3.1.3 on 2020-12-10 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0019_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_book', models.PositiveIntegerField(verbose_name='rate_book')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_user_table', to='manager.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_book_table', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
