# Generated by Django 3.1.3 on 2020-12-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('manager', '0021_book_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='likebookuser',
            name='rate',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
