# Generated by Django 3.1.3 on 2020-12-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_likebookuser_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rates',
        ),
        migrations.DeleteModel(
            name='RateBook',
        ),
    ]
