# Generated by Django 3.1.3 on 2020-12-28 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_auto_20201219_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_genre', models.TextField()),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='manager.book')),
            ],
        ),
    ]
