# Generated by Django 3.1.3 on 2020-12-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='book',
        ),
    ]
