# Generated by Django 3.1.3 on 2020-12-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_remove_genre_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='genre_of_book', to='manager.Genre'),
        ),
    ]
