# Generated by Django 3.1.3 on 2020-12-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0035_auto_20201228_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='genre_of_book', to='manager.Genre', verbose_name='Жанр'),
        ),
    ]
