# Generated by Django 3.1.3 on 2021-01-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0039_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='manager/'),
        ),
    ]
