# Generated by Django 3.1.3 on 2021-01-08 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0043_auto_20210108_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_repos', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
