# Generated by Django 3.1.3 on 2021-01-15 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0044_gitrepos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_account', models.CharField(max_length=100, null=True)),
                ('_title_repos', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repos_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='gittoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='GitRepos',
        ),
        migrations.DeleteModel(
            name='GitToken',
        ),
    ]
